import Head from "next/head";
import type { Session } from "next-auth";
import ThemeSwitch from "./ThemeSwitch";
import HeaderProfileButton from "./HeaderProfileButton";

type HeaderProps = {
  title: string;
  sessionData: Session | null;
};

const Header = (props: HeaderProps) => {
  return (
    <>
      <Head>
        <title>{props.title}</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className="flex items-center justify-end gap-2">
        <ThemeSwitch />
        <HeaderProfileButton sessionData={props.sessionData} />
      </header>
    </>
  );
};

export default Header;
